%Scale-space blob detector

img=imread('image.jpg');
img=rgb2gray(img);

sigma=10;
x=floor(3*sigma);
y=floor(3*sigma);
Gauss=zeros(2*x+1,2*y+1);
%Guassian kernel
%for u=1:2*x+1
%    for v=1:2*y+1;
%        Gauss(u,v)=1/2/pi/(sigma^2)*exp((-(u-x-1)^2-(v-x-1)^2)/(2*sigma^2));
%    end
%end
%a little error with the Gaussian kernel generated by fspecial

%Another Guassian kernel, this is the right answer
for u=1:2*x+1
    for v=1:2*y+1;
        Gauss(u,v)=exp((-(u-x-1)^2-(v-x-1)^2)/(2*sigma^2));
    end
end
sum_Gauss=sum(sum(Gauss));
Gauss=Gauss./sum_Gauss;

alpha=0.2;
laplacian=4/(1+alpha)*[alpha/4,(1-alpha)/4,alpha/4;(1-alpha)/4,-1,(1-alpha)/4;alpha/4,(1-alpha)/4,alpha/4];

S=conv2(double(img),Gauss,'same');%direct convolution will not cause any confusion. 
%But the number of multiplication in the convolution will change when the window approach to the edge of the image

%S=conv2(S,laplacian,'same');
imshow(S,[]);